import { getEnvVal } from "../utils/env-utils";

const ACCESS_TOKEN_SECRET_KEY = getEnvVal("ACCESS_TOKEN_SECRET_KEY");
const REFRESH_TOKEN_SECRET_KEY = getEnvVal("REFRESH_TOKEN_SECRET_KEY");

const ACCESS_TOKEN_DURATION_IN_MS = 60000;
const REFRESH_TOKEN_DURATION_IN_MS = 31557600000;

export {
  ACCESS_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_SECRET_KEY,
  ACCESS_TOKEN_DURATION_IN_MS,
  REFRESH_TOKEN_DURATION_IN_MS,
};
